# -*- coding: utf-8 -*-
"""
Created on Sat Aug 31 13:08:51 2019

@author: Samuel
"""
import numpy as np
import matplotlib.pyplot as plt



# Function that calculates the nth number in the collatz sequence 
def collatz(n):
    if n%2==0:
        return n//2
    else:
        return 3*n+1

# m = int(input('Enter number: '))   




# Function that stores the collatz seqeunce generated by m in a list
# def collatz_sequence(x):
#     global m
#     while collatz(m)!=1:
#         if collatz(m)!= 1:
#            x.append(m)
#            m = collatz(m)
#     x.append(1)       

    



def collatz_seq_gen_by(n):
    x = []
    if collatz(n) == 1:
        x.append(n)
    while collatz(n)!=1:
        if collatz(n)!= 1:
           x.append(n)
           n = collatz(n)
    x.append(1)
    return x       



data_seq = dict() 
empty_list = dict()

for k in range(1,10000):
    for i in range(1,10000):
        data_seq[i] = collatz_seq_gen_by(i) 
        empty_list[i] = []
        for j in range(1,len(data_seq[i])+1):
            empty_list[i].append(j)
    plt.scatter(empty_list[k],data_seq[k])
plt.show()            


    




    
    
    
    
    