# -*- coding: utf-8 -*-
"""
Created on Sat Aug 31 13:08:51 2019

@author: Samuel
"""


# Function that calculates the nth number in the collatz sequence 
def collatz(n):
    if n%2==0:
        return n//2
    else:
        return 3*n+1

m = int(input('Enter number: '))   


x = []

# Function that stores the collatz seqeunce generated by m in a list
def collatz_sequence(x):
    global m
    while collatz(m)!=1:
        if collatz(m)!= 1:
           x.append(m)
           m = collatz(m)
    x.append(1)       

    
a = []
b = []
c = []


def collatz_seq_gen_by(n):
    x = []
    if collatz(n) == 1:
        x.append(n)
    while collatz(n)!=1:
        if collatz(n)!= 1:
           x.append(n)
           n = collatz(n)
    x.append(1)
    return x       



data_seq = dict() 


import numpy as np
import matplotlib.pyplot as plt

x = []
for i in range(1,4):
    data_seq[i] = collatz_seq_gen_by(i)

for j in range(len(data_seq[j])):
    plt.plot(data_seq[j])
plt.legend()
plt.show()
    
    
    





    
    
    
    
    